apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: {{ .Values.namespace }}
  labels:
    app: loadgenerator
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: main
          image: "{{ .Values.loadgenerator.image }}:{{ .Values.loadgenerator.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
            - name: USERS
              value: "{{ .Values.loadgenerator.users }}"
          resources:
            {{- toYaml .Values.loadgenerator.resources | nindent 12 }}
